networks:
  cloudflared:
    external: true

services:
  murmur-server:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ${PRODUCTION_IMAGE:-murmur-server:production}
    container_name: ${PRODUCTION_CONTAINER_NAME:-murmur-server-production}
    restart: always
    environment:
      DATABASE_URL: ${PRODUCTION_DATABASE_URL:-/var/app/data/production.sqlite3}
      PORT: ${PRODUCTION_CONTAINER_PORT:-3000}
      BIND_ADDR: 0.0.0.0:${PRODUCTION_CONTAINER_PORT:-3000}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    volumes:
      - murmur-production-data:/var/app/data
    networks:
      cloudflared:
        ipv4_address: ${PRODUCTION_IPV4_ADDRESS:-10.5.123.123}


volumes:
  murmur-production-data:
